const corona = [
    {
        month: "März 20",
        hotels_badenWuerttemberg: 0,
        hotels_bayern: 0,
        hotels_brandenburg: 0,
        hotels_bremen: 0,
        hotels_hamburg: 0,
        hotels_hessen: 0,
        hotels_mecklenburgVorpommern: 0,
        hotels_niedersachsen: 0,
        hotels_nordrheinWestfalen: 0,
        hotels_rheinlandPfalz: 0,
        hotels_saarland: 0,
        hotels_sachsen: 0,
        hotels_sachsenAnhalt: 0,
        hotels_schleswigHolstein: 0,
        hotels_thueringen: 0,
    },
    {
        month: "April 20",
        hotels_badenWuerttemberg: 1,
        hotels_bayern: 1,
        hotels_brandenburg: 1,
        hotels_bremen: 1,
        hotels_hamburg: 1,
        hotels_hessen: 1,
        hotels_mecklenburgVorpommern: 1,
        hotels_niedersachsen: 1,
        hotels_nordrheinWestfalen: 1,
        hotels_rheinlandPfalz: 1,
        hotels_saarland: 1,
        hotels_sachsen: 1,
        hotels_sachsenAnhalt: 2,
        hotels_schleswigHolstein: 2,
        hotels_thueringen: 1,
    },
    {
        month: "Mai 20",
        hotels_badenWuerttemberg: 1,
        hotels_bayern: 1,
        hotels_brandenburg: 1,
        hotels_bremen: 1,
        hotels_hamburg: 1,
        hotels_hessen: 1,
        hotels_mecklenburgVorpommern: 1,
        hotels_niedersachsen: 1,
        hotels_nordrheinWestfalen: 1,
        hotels_rheinlandPfalz: 1,
        hotels_saarland: 1,
        hotels_sachsen: 1,
        hotels_sachsenAnhalt: 1,
        hotels_schleswigHolstein: 2,
        hotels_thueringen: 1,
    }
]

export default corona;    